#!/bin/bash

clear 
printf "\n"
read -p "How many  characters would you like your password?" pass_length
printf "\n"

#Before alumn i added special characters

for i in {1..8}; do (tr -cd '[!"£$^&*+[:alnum:]]' < /dev/urandom | fold -w${pass_length} | head -n 1) >passwords.txt;
done

printf "$pass_output\n" 
printf "Goodbye, ${USER}\n"

